section_retrieval_prompts = {
    "Business Information": ("Company overview, industry structure, core business segments, product and service portfolio, market position, domestic and global presence, key subsidiaries, joint ventures, revenue drivers, and notable achievements or milestones for the fiscal year."),
    "Corporate Information": ("List of Board of Directors and their designations (Executive, Non-Executive, Independent), Key Managerial Personnel (KMP) including CEO, CFO, and Company Secretary. Details of the registered office, auditors, bankers, and stock exchange listing information with ISIN codes."),
    "Chairman's Letter": ("The full text of the Chairman's Message, Letter from the Chairman, or Statement to Shareholders or Statement to Stakeholders. Covering the company's vision, year's highlights, financial performance, and future outlook."),
    "Board's Report": ("The complete Board's Report or Directors' Report. Covering the state of the company's affairs, financial summary, dividends, reserves, Corporate Social Responsibility (CSR) initiatives and expenditure, risk management framework, and internal audit compliance."),
    "Shareholding Information": ("The detailed Shareholding Pattern for the year. Data showing Promoter vs Public shareholding percentages, breakdown of Foreign Institutional Investors (FIIs), Domestic Institutional Investors (DIIs), and retail ownership. Lists of top ten shareholders and data on share price performance."),
    "Corporate Governance": ("The 'Report on Corporate Governance'. Details on board composition, director independence, gender diversity, number of board and committee meetings held, compliance with SEBI and NSE corporate governance norms, and remuneration disclosures for directors and KMP."),
    "Management Discussion and Analysis": ("The complete 'Management Discussion and Analysis' (MD&A) section. Analysis of industry outlook, segment-wise financial and operational performance, SWOT analysis, discussion on key risks and mitigation strategies, and future growth plans including CAPEX or R&D investments."),
    "Consolidated Financial Statements": ("The complete Audited Consolidated Financial Statements. Specifically the Balance Sheet showing assets and liabilities, the Statement of Profit and Loss (P&L) with revenue and PAT, and the Cash Flow Statement detailing operating, investing, and financing activities. Includes notes to accounts and key financial ratios.")
}

section_summary_prompts = {
    "Business Information": ("Act as a business analyst. From the context, provide a concise overview of the company. Start with a single sentence defining its core business and market position. Then, in bullet points, list its primary revenue drivers (by product/geography) and any notable achievements or milestones from the past year."),
    "Corporate Information": ("Act as a compliance officer. Extract and list the following key details: 1. Registered Office Address. 2. Full names of the CEO, CFO, and Company Secretary. 3. Name of the Statutory Auditors. 4. Stock Exchanges where the company is listed, along with its ISIN code."),
    "Chairman's Letter": ("Act as an investment strategist. Analyze the Chairman's Letter and summarize it in 4-5 crisp bullet points, focusing on forward-looking statements. Capture the overall performance summary, the management's view on the macroeconomic context, key strategic priorities for the future, and the core message to shareholders. If chairman's letter is not present summarize the letter from CEO."),
    "Board's Report": ("Act as a financial journalist. From the Board's Report, extract only the most critical shareholder-relevant information. In bullet points, state the: 1. Declared dividend per share. 2. Total CSR expenditure and whether it complies with regulations. 3. Any major board decisions regarding mergers, acquisitions, or significant expansions."),
    "Shareholding Information": ("Act as a market analyst. From the shareholding data, provide a clear snapshot of the ownership structure. In bullet points, state the: 1. Promoter vs. Public shareholding percentage. 2. A trend summary for FII and DII participation if available. 3. The company's dividend yield and payout ratio for the year."),
    "Corporate Governance": ("Act as a governance watchdog. From the Corporate Governance report, highlight key transparency and ethical practice indicators. In bullet points, state the: 1. Board's independence ratio (number of independent directors vs. total). 2. The number of board meetings held during the fiscal year. 3. The key highlight or finding from the auditor's report on governance."),
    "Management Discussion and Analysis": ("Act as a senior business analyst. Distill the MD&A into a strategic summary. Provide a brief paragraph on the management's outlook on the industry and competition. Then, using bullet points, clearly list the top 3 strengths/opportunities and the top 3 weaknesses/threats (SWOT) that the management has identified."),
    "Consolidated Financial Statements": ("Act as a financial health inspector. Highlight YoY trends from the financial statements. In bullet points, state the: 1. Trend in Total Revenue (e.g., 'Increased by X% YoY'). 2. Trend in Profit After Tax (PAT). 3. The trend in Net Cash from Operating Activities. 4. Key ratios like ROE and the Debt-to-Equity ratio, and mention if they have improved or declined.")
}